---
- hosts: dockerhost
  become: false
  gather_facts: false
  vars_files:
  - vault_common.yml
  vars:
    become_pass: "{{ sudo_password }}"
    postgres_pass: "{{ db_password }}"

  tasks:
  - name: Create a db network in Docker
    docker_network:
      name: db_net

  - name: Create a db Volume in Docker
    docker_volume:
      name: db_vol

  - name: Build Fast-API PostGres db image for Docker
    docker_image:
      build: 
        path: ./postgres
        pull: yes
      source: build
      force_source: yes
      state: present
      name: fast_api_db_img

  - name: Create the Docker Container from the image
    docker_container:
      name: fast_api_db_01
      image: fast_api_db_img
      purge_networks: yes
      networks:
        - name: db_net
          aliases:
          - postgres
      volumes:
        - "db_vol:/var/lib/postgresql/data"
      env:
        POSTGRES_PASSWORD: "{{ postgres_pass }}"

- hosts: postgres_db
  become: no
  gather_facts: yes
  tasks:
    - name: ping the new docker containers
      ping:

    - name: Print the gateway for each host when defined
      debug:
        msg: System {{ inventory_hostname }} has gateway {{ ansible_python_version }}
      when: ansible_python_version is defined