FROM alpine:latest
 
ENV DEBIAN_FRONTEND=noninteractive
 
RUN apt-get update && \
 apt-get install -y gcc && \
 apt-get install python3-pip -y && \
 pip3 install --upgrade pip && \
 pip3 install --upgrade virtualenv && \
 pip3 install ansible